# Generated by Django 4.1.4 on 2022-12-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('slag', models.SlugField(unique=True, verbose_name='Уникальное обозначение')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('slag', models.SlugField(unique=True, verbose_name='Уникальное обозначение')),
            ],
        ),
        migrations.CreateModel(
            name='SecondLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('slag', models.SlugField(unique=True, verbose_name='Уникальное обозначение')),
                ('first_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_level', to='menu.firstlevel', verbose_name='Первый уровень')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('slag', models.SlugField(unique=True, verbose_name='Уникальное обозначение')),
                ('second_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_level', to='menu.secondlevel', verbose_name='Первый уровень')),
            ],
        ),
        migrations.AddField(
            model_name='firstlevel',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_level', to='menu.menu', verbose_name='Первый уровень'),
        ),
    ]
