# Generated by Django 4.1.4 on 2022-12-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_firstlevel_name_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstlevel',
            options={'verbose_name': 'Первый уровень', 'verbose_name_plural': 'Первые уровни'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='secondlevel',
            options={'verbose_name': 'Второй уровень', 'verbose_name_plural': 'Вторые уровни'},
        ),
        migrations.AlterModelOptions(
            name='thirdlevel',
            options={'verbose_name': 'Третий уровень', 'verbose_name_plural': 'Третьи уровни'},
        ),
    ]
