# Generated by Django 4.1.4 on 2022-12-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_firstlevel_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstlevel',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='secondlevel',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='thirdlevel',
            old_name='slag',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='firstlevel',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_level', to='menu.menu', verbose_name='Меню'),
        ),
    ]
